name: LMAONetwork
version: 1.15.7
main: pro.delfik.lmao.core.Lmao
author: DelfikPro
softdepend: [ImplarioLib]
loadbefore: [LmaoLobby]
load: POSTWORLD
commands:
  admin:
    aliases: [a]
  perms:
  vanish:
  invsee:
  gamemode:
    aliases: [gm1, gm0, gm3, gmc, gmw, gms, gm]
  tp:
    aliases: [teleport]
  help:
  player:
    aliases: [p, me]
  vanish:
    aliases: [v]
  sudo:
  list:
  stop:
  actions:
  sch: